language: c
cache: ccache
compiler:
  - gcc
  - clang

dist: xenial

os:
  - linux

arch:
  - amd64
  - ppc64le
#  - arm64

addons:
  apt:
    update: true
    packages: &required_packages
      - [libnuma-dev, linux-headers-$(uname -r), python3-setuptools, python3-wheel, python3-pip, ninja-build]

before_install: ./.ci/${TRAVIS_OS_NAME}-setup.sh

env:
  - DEF_LIB="static"
  - DEF_LIB="shared"
  - DEF_LIB="static" OPTS="-Denable_kmods=false"
  - DEF_LIB="shared" OPTS="-Denable_kmods=false"
  - DEF_LIB="static" EXTRA_PACKAGES=1
  - DEF_LIB="shared" EXTRA_PACKAGES=1
  - DEF_LIB="static" OPTS="-Denable_kmods=false" EXTRA_PACKAGES=1
  - DEF_LIB="shared" OPTS="-Denable_kmods=false" EXTRA_PACKAGES=1
  - DEF_LIB="shared" RUN_TESTS=1
  - DEF_LIB="shared" EXTRA_PACKAGES=1 RUN_TESTS=1

matrix:
   exclude:
   - arch: ppc64le
     env: DEF_LIB="shared" RUN_TESTS=1
   - arch: ppc64le
     env: DEF_LIB="shared" EXTRA_PACKAGES=1 RUN_TESTS=1
   - arch: arm64
     env: DEF_LIB="shared" RUN_TESTS=1
   - arch: arm64
     env: DEF_LIB="shared" EXTRA_PACKAGES=1 RUN_TESTS=1

   include:
   - arch: amd64
     env: DEF_LIB="static" OPTS="-Denable_kmods=false" AARCH64=1
   - arch: amd64
     env: DEF_LIB="shared" OPTS="-Denable_kmods=false" AARCH64=1
   - arch: amd64
     env: DEF_LIB="shared" BUILD_DOCS=1

script: ./.ci/${TRAVIS_OS_NAME}-build.sh
