# default values for all jobs
language: c
cache:
  ccache: true
  directories:
    - libabigail
    - reference

dist: bionic

os: linux

addons:
  apt:
    update: true
    packages: &required_packages
      - [libnuma-dev, python3-setuptools, python3-wheel, python3-pip, ninja-build]
      - [libbsd-dev, libpcap-dev, libibverbs-dev, libcrypto++-dev, libfdt-dev, libjansson4]

_aarch64_packages: &aarch64_packages
  - *required_packages
  - [gcc-aarch64-linux-gnu, libc6-dev-arm64-cross, pkg-config-aarch64-linux-gnu]

_libabigail_build_packages: &libabigail_build_packages
  - [autoconf, automake, libtool, pkg-config, libxml2-dev, libdw-dev]

_build_32b_packages: &build_32b_packages
  - *required_packages
  - [gcc-multilib]

_doc_packages: &doc_packages
  - [doxygen, graphviz, python3-sphinx]

before_install: ./.ci/${TRAVIS_OS_NAME}-setup.sh
script: ./.ci/${TRAVIS_OS_NAME}-build.sh

env:
  global:
    - REF_GIT_TAG=v20.02

jobs:
  include:
  # ppc64le gcc jobs
  - env: DEF_LIB="static"
    arch: ppc64le
    compiler: gcc
  - env: DEF_LIB="shared" BUILD_DOCS=1
    arch: ppc64le
    compiler: gcc
    addons:
      apt:
        packages:
          - *required_packages
          - *doc_packages
  - env: DEF_LIB="shared" ABI_CHECKS=1
    arch: ppc64le
    compiler: gcc
    addons:
      apt:
        packages:
          - *required_packages
          - *libabigail_build_packages
